### ISSUE TITLE
Question about whitelisting

### ISSUE THREAD

**Issue by Dagnan** [flyerhzm/bullet#106]
Hi.

Is it possible to whiletelist a block of code? I mean is it something that the architecture of Bullet would allow. If so I'd be interested to implement this feature.

I think it is more correct to talk about "ignoring" bullet for a block of code.

I have complex associations and the whitelisting feature does not totally work on them. Plus, I would like to ignore the notices in some parts of my app and not in others.

**Comment by anthonator** [comment]
I raise Bullet errors when testing. This causes headaches for complex associations that I want to ignore. Whitelisting associations on models globally isn't really an option. Whitelisting controllers might work. What would be awesome is if we could write a comment to ignore a line similar to linters like jshint but that's probably not feasible.

**Comment by anthonator** [comment]
Maybe if there was some sort of rspec integration that would allow us to whitelist for a specific test. That would be awesome.

**Comment by softcraft-development** [comment]
Global whitelisting is definitely problematic. You're pretty much guaranteeing to hide legitimate problems somewhere in your code.

I also agree that it's not a terribly good idea to have Bullet active in the Production gemsets (though that should be inconsequential if it's disabled by default). Perhaps a solution would be to add additional parameters to the `add_whitelist` call that take `:controller` and `:action` ?

**Comment by flyerhzm** [comment]
if you want to disable bullet for specific action, you can add `around_action`, like

```
class PostsController < ApplicationController
   around_action :skip_bullet

  def skip_bullet
    Bullet.enable = false
    yield
  ensure
    Bullet.enable = true
  end
end
```

**Comment by AlexVPopov** [comment]
@flyerhzm but this results in an error, as `Bullet` is not defined in production? Do you mean, that `skip_bullet` is intended to be added only while developing, but never merged into production code? I guess the `around_action` should have an `if` clause with something like `if: -> { defined?(Bullet) }`

**Comment by flyerhzm** [comment]
@AlexVPopov yes, you are right
