### ISSUE TITLE
Bullet with rspec

### ISSUE THREAD

**Issue by exalted** [flyerhzm/bullet#115]
Is it possible to bullet make spec tests fail if there are issues detected by bullet gem please?

**Comment by santi-h** [comment]
Is this possible now? I've been googling around for a bit and could not find a straightforward answer.

**Comment by flyerhzm** [comment]
@santi-h you can set `Bullet.raise` to true, then it will raise an error when an n+1 query is detected and make a test failure.

**Comment by santi-h** [comment]
how about that for a straightforward answer! thanks a lot man

**Comment by ritaamritkar1212** [comment]
can someone please help me how the test vase can be written to detect the N+1 using Bullet gem?
