### ISSUE TITLE
False N+1 Query detected using factories?

### ISSUE THREAD

**Issue by exalted** [flyerhzm/bullet#120]
Enabled bullet in test mode, using factory_girl in specs through rspec, I have this case where a “N+1 Query” gets detected in a controller spec, although I think it shouldn’t be there (or simply: I don’t understand why it’s detected in the first place).

I will try to paste below some code snippets to give you an idea, trying to skip the irrelevant parts.

This is the spec:

``` ruby
describe ResourcesController do
  context 'when a signed in user access another user collection' do
    it 'should not be able to delete a Resource' do
      resource = create(:resource1)
      sign_in create(:registered_user)

      expect do
        delete :destroy, collection: resource.collection.slug, username: resource.collection.user.username, resource: resource.id
      end.to raise_error(ActionController::RoutingError)
    end
  end
end
```

> N+1 is on `resource.collection.user.username` above.

… and the controller:

``` ruby
class ResourcesController < ApplicationController

  # ...

  def destroy
    Resource.find(params[:resource]).destroy
    redirect_to edit_collection_url(params[:username], params[:collection])
  end

  # ...

end
```

At last, below are the relevant parts for the factories:

``` ruby
FactoryGirl.define do
  factory :oauth_user, class: :user do
    factory :registered_user, class: :user do
    end
  end

  factory :valid_collection, class: :collection do
    association :user, factory: :registered_user
  end

  factory :resource_without_items, class: :resource do
    association :collection, factory: :valid_collection
    user { |element| element.collection.user }

    factory :resource1, class: :resource do
    end
  end
end
```

At this point tests run just fine, but bullet will report:

```
2013-08-28 16:18:54[WARN] user: username

N+1 Query detected
  Collection => [:user]
  Add to your finder: :include => [:user]
N+1 Query method call stack
  N+1 Query method call stack
  /Users/username/Development/foobar/spec/controllers/resources_authorization_spec.rb:10:in `block (4 levels) in <top (required)>'
  /Users/username/Development/foobar/spec/controllers/resources_authorization_spec.rb:9:in `block (3 levels) in <top (required)>'
```

I believe, factory_girl generates first the resource, then the collection (through the `:collection` association) and the user (through `:user` association).

I have no idea where the N+1 query is though.

Any ideas? Thanks.

**Comment by ndbroadbent** [comment]
This is still an issue for me. @yachi's solution works really well, so now I'm only profiling my controller actions. But it would be nice if Bullet could ignore any fixtures that are created with FactoryBot.
