### ISSUE TITLE
Bullet should not be calling response.body

### ISSUE THREAD

**Issue by jshraibman-mdsol** [flyerhzm/bullet#125]
In my code I set response_body to an Enumerator to stream a large generated file to the user.  The problem is that bullet calls response.body not once, but twice, in rack.rb.

Stack trace (both are identical, since they happen on the same line):

```
/Users/jshraibman/.rvm/gems/ruby-1.9.3-p448/gems/actionpack-3.0.20/lib/action_dispatch/http/response.rb:154:in `each'
/Users/jshraibman/.rvm/gems/ruby-1.9.3-p448/gems/actionpack-3.0.20/lib/action_dispatch/http/response.rb:154:in `each'
/Users/jshraibman/.rvm/gems/ruby-1.9.3-p448/gems/actionpack-3.0.20/lib/action_dispatch/http/response.rb:154:in `each'
/Users/jshraibman/.rvm/gems/ruby-1.9.3-p448/gems/actionpack-3.0.20/lib/action_dispatch/http/response.rb:101:in `body'
/Users/jshraibman/.rvm/gems/ruby-1.9.3-p448/gems/bullet-4.6.0/lib/bullet/rack.rb:51:in `response_body'
/Users/jshraibman/.rvm/gems/ruby-1.9.3-p448/gems/bullet-4.6.0/lib/bullet/rack.rb:34:in `empty?'
/Users/jshraibman/.rvm/gems/ruby-1.9.3-p448/gems/bullet-4.6.0/lib/bullet/rack.rb:14:in `call'
```

bullet needs to guard against this somehow.  Everytime response.body is called the Enumerator is cycled through and all of its output concatenated into a string.  As a short term fix please cache the result of the response.body call so at least it is only being called once.

**Comment by flyerhzm** [comment]
bullet doesn't call response.body any more if it serves a file
