### ISSUE TITLE
Detects N+1, then says unused eager loading.  

### ISSUE THREAD

**Issue by CyborgMaster** [flyerhzm/bullet#147]
I've got a query running on one of my pages that needs eager loading.  When I don't do any includes, Bullet correctly detects the N+1 query and displays the following warning:

```
user: jeremy N+1 Query detected Appointment => [:practice] Add to your finder: :include => [:practice]
user: jeremy N+1 Query detected Appointment => [:patient] Add to your finder: :include => [:patient]
```

So I add this line to the query:

``` ruby
.includes(:patient, practice: :ext)
```

But then Bullet erroneously detects an unused eager loading and gives the following message:

```
user: jeremy Unused Eager Loading detected Appointment => [:patient, :practice] Remove from your finder: :include => [:patient, :practice]
user: jeremy Unused Eager Loading detected Practice => [:ext] Remove from your finder: :include => [:ext]
```

Any idea why it might be doing this or where I should look to start debugging?

**Comment by tborisova** [comment]
I get this on Rails 3.0.20 and latest bullet version

**Comment by lzap** [comment]
A sidenote - we saw this in the situation when we had dual association. In our case it was host.subnet_id -> subnet and host.interface[X].subnet_id -> subnet. If we added includes(:subnet) we were having those kind of issues, the correct way was to ignore the "extra" association going strictly with includes({:interfaces => :subnet}). Hope this makes any sense.

**Comment by DaniG2k** [comment]
I've experienced a similar issue (Rails 4.2.5, Bullet 4.14.10) which I've described in full on this [StackOverflow thread](http://stackoverflow.com/questions/34632376/rails-4-small-n1-issue-for-uncached-page).

**Comment by Freika** [comment]
Same issue here on Rails 5.0.0, Bullet 5.4.2.

relations:

```
# Map
class Map < ApplicationRecord
  has_many :destinations
  has_many :matches, through: :destinations
end

# Match
class Match < ApplicationRecord
  has_one :destination
  has_one :map, through: :destination
end

# Destination
class Destination < ApplicationRecord
  belongs_to :map
  belongs_to :match
end
```

Before:

```
@matches = Match.order(created_at: :asc)
````
result: 
>user: frey  N+1 Query detected    Match => [:map]
>  Add to your finder: :includes => [:map]

after:

```
@matches = Match.includes(:map).order(created_at: :asc)
```

result:

>user: frey  Unused Eager Loading detected    Match => [:destination]
>  Remove from your finder: :includes => [:destination]
>user: frey  Unused Eager Loading detected    Destination => [:map]
>  Remove from your finder: :includes => [:map]

**Comment by Gokul595** [comment]
Same issue occurring form me.

Rails: 5.1.4, Ruby: 2.4.3 and Bullet: 5.7.2

**Comment by henners66** [comment]
Also experiencing the same:

Rails 5.1.4, Ruby 2.4.2 and Bullet 5.7.2

**Comment by IvikGH** [comment]
Have same issue
gem 'rails', '4.2.5'
bullet (5.7.5)

**Comment by alfuken** [comment]
Same here. Also, gem ignores `Bullet.unused_eager_loading_enable = false` which is just plain ridiculous.

**Comment by Bergrebell** [comment]
same here.
rails: 5.1.6
ruby: 2.5.1
bullet-gem: 5.7.5

although `Bullet.unused_eager_loading_enable = false` worked for me.

**Comment by ziaulrehman40** [comment]
Same issue on rails 4.2 and latest bullet gem, i don't want to disable `unused_eager_loading_enable` check for one place like this. @flyerhzm any suggestions?
Or anyone else would like to share their experience?

**Comment by ziaulrehman40** [comment]
Thanks for responding @alfuken ,
But I disagree, IMHO if rails does find say 2k records and i have extra includes of a has_many association, rails WILL go ahead and load all the associated association records into the memory even if we use it or not. So this `unused_eager_loading` is indeed very important.
but this is an issue needing resolution and i will urge @flyerhzm to reopen this issue. As many have reported same issue and this should be re-opened at-least, so it can be queued in todos and someone can fix it.

**Comment by flyerhzm** [comment]
does this PR https://github.com/flyerhzm/bullet/pull/433 fix rails 5.x issue?

**Comment by ziaulrehman40** [comment]
@flyerhzm Thanks for following up, how can i test with this commit 🤔

**Comment by flyerhzm** [comment]
@ziaulrehman40 I just released bullet 5.8.0, please try it.

**Comment by ziaulrehman40** [comment]
Just tested, i am on rails 4.2.10, issue is persistent, not solved by the update. We should re-open this bug IMO.

**Comment by flyerhzm** [comment]
@ziaulrehman40 this PR is only for rails 5.x, I'll see if I can apply it for rails 4.x

**Comment by brunoparga** [comment]
@flyerhzm I'm running into the same problem with bullet 5.9.0 and rails 5.2.2.

**Comment by KhadeevKamil** [comment]
@flyerhzm 

my model has 

```  has_many :subcategories,
    class_name: "Category",
    foreign_key: :parent_category_id,
    inverse_of: :parent_category,
    validate: false

  belongs_to :parent_category,
    class_name: "Category",
    inverse_of: :categories,
    index: true,
    validate: false,
    optional: true
```

controller:

```
expose :resources_scope, -> { resource_class.includes([:subcategories]) }
```

But when I run rspec test i have exeption 

```
GET /api/v1/admin/categories/5c7ea8f892991879e86b973e
USE eager loading detected
  Category => [:subcategories]
  Add to your finder: :includes => [:subcategories]
Call stack
```

**Comment by nnat425** [comment]
> A sidenote - we saw this in the situation when we had dual association. In our case it was host.subnet_id -> subnet and host.interface[X].subnet_id -> subnet. If we added includes(:subnet) we were having those kind of issues, the correct way was to ignore the "extra" association going strictly with includes({:interfaces => :subnet}). Hope this makes any sense.

This worked for me. Thanks.

**Comment by virajvchavan** [comment]
I have the same problem. (Rails 7, Ruby 3.0.2, Bullet 7.0.1)

**Comment by ThaiGQ** [comment]
Likewise. I am running into this issue with my minitest:

```
class Review < ApplicationRecord
  belongs_to :account_user
  belongs_to :product
  has_one :brand, through: :product
  has_rich_text :body

  # Broadcast changes in realtime with Hotwire
  after_create_commit -> { broadcast_prepend_later_to :reviews, partial: "reviews/index", locals: {review: self} }
  after_update_commit -> { broadcast_replace_later_to self }
  after_destroy_commit -> { broadcast_remove_to :reviews, target: dom_id(self, :index) }

  # validations
  validates :product_id, uniqueness: {scope: :account_user_id}
  validates :title, presence: true
  validates :rating, presence: true, numericality: {only_integer: true, in: 1..5}

  # Delegations
  delegate :name, to: :account_user, prefix: true
  delegate :name, to: :brand, prefix: true
  delegate :name, to: :product, prefix: true
end

Review.includes(
        {
          account_user: :user,
        },
        :product,
        :rich_text_body
      ).sort_by_params(params[:sort], sort_direction)

Error:
ReviewsControllerTest#test_: when signed in index should be able to view all reviews. :
Bullet::Notification::UnoptimizedQueryError: user: ekapob
GET /reviews
USE eager loading detected
  Product => [:brand]
  Add to your query: .includes([:brand])
```

When I add the `brand` to my query:

```
Review.includes(
        {
          account_user: :user,
          # product: :brand
        },
        :product,
        :brand,
        :rich_text_body
      ).sort_by_params(params[:sort], sort_direction)

Error:
ReviewsControllerTest#test_: when signed in index should be able to view all reviews. :
Bullet::Notification::UnoptimizedQueryError: user: ekapob
GET /reviews
AVOID eager loading detected
  Product => [:brand]
  Remove from your query: .includes([:brand])
```

I'm on Ruby 3.1.2, Rails 7.0.4, Bullet 7.0.3
