### ISSUE TITLE
cannot get bullet errors in custom environments

### ISSUE THREAD

**Issue by thijsnado** [flyerhzm/bullet#184]
Tried creating a new environment called development_with_debug that includes bullet and has the following in the after_initialize block

``` ruby
  config.after_initialize do
    Bullet.enable = true
    #Bullet.alert = true
    Bullet.bullet_logger = true
    Bullet.console = true
    #Bullet.growl = true
    Bullet.rails_logger = true
    if ENV["HIDE_BULLET_PROFILER"] == 'true'
      Bullet.add_footer = false
    else
      Bullet.add_footer = true
    end

    if ENV["PROFILE_STRICT"] == 'true'
      Bullet.raise = true
    end

    if ENV["HIDE_BULLET_PROFILER"] == 'true'
      Bullet.add_footer = false
    end
  end
```

this works when done in development.rb but the same thing won't work with development_with_debug.rb

**Comment by pierre-pretorius** [comment]
I had the same issue with an environment named profile.  Moving the gem in the gemfile to group: 'profile' solved the problem.
