### ISSUE TITLE
Bullet doesn't work with rails 4.1.5 and Mongoid 4.0.0

### ISSUE THREAD

**Issue by deXterbed** [flyerhzm/bullet#185]
I get this error when i run `bin/rails server`:

``` ruby
/gems/bullet-4.13.1/lib/bullet.rb:48:in `enable=': uninitialized constant Bullet::Mongoid (NameError)
```

**Comment by apellizzn** [comment]
+1 for this,
it says  ```uninitialized constant Bullet::Mongoid (NameError)``` monoid: v4.0.0, rails: v4.0.9
