### ISSUE TITLE
bullet and RspecApiDocumentation

### ISSUE THREAD

**Issue by ghost** [flyerhzm/bullet#195]
I'm trying to use Bullet and also [RspecApiDocumentation](https://github.com/zipmark/rspec_api_documentation).

The Issue I have is probably half bullet and half RAD related, but I thought I first ask here, because you might know what I can do. Everything runs fine except when I try to create the documentation docs with RAD. It gives me:

```
Users/sly/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bullet-4.14.0/lib/bullet.rb:49:in `enable=': uninitialized constant Bullet::ActiveRecord (NameError)
```

RAD is started via an Rake Task. Do you have any idea what is causing this issue and how to solve this? Thank you!

**Comment by rafaelgonzalez** [comment]
Stumble upon this problem just today when running my specs.

@pgoetze's solution works for me, but I find it a bit ridiculous to have to require active_record.

This should be reopened.

```ruby
# config/environments/test.rb
# Bullet configuration
config.after_initialize do
  Bullet.enable = true
  Bullet.raise = true
end
```

**Comment by pgoetze** [comment]
:+1: @rafaelgonzalez

**Comment by michaeldever** [comment]
👍 @rafaelgonzalez
