### ISSUE TITLE
app error: deadlock; recursive locking (ThreadError) with Rack

### ISSUE THREAD

**Issue by KelseyDH** [flyerhzm/bullet#200]
When I use bullet in Rails 3.1.12 in local development with Unicorn I get this issue with Rack when loading a page.  When I notified the maintainers of Rack they pointed me (https://github.com/rack/rack/issues/658#issuecomment-67217697) to the recent changes to Bullet::Rack as a likely cause.  E.g. recent changes to this file:  https://github.com/flyerhzm/bullet/blob/master/lib/bullet/rack.rb

Do you know what it might be that's causing this issue?

**Comment by BenMorganIO** [comment]
I don't see any explicit threading going on inside of `Bullet::Rack`, but I'm guessing its core rack that's doing the threading.

There's actually some threading happening in the `Bullet.end_request` which is called [here](https://github.com/flyerhzm/bullet/blob/master/lib/bullet/rack.rb#L28-L30) and, with threads in all its glory, defined [here](https://github.com/flyerhzm/bullet/blob/ad152e0fe835b3667dcd2e14b35696fd47354bd7/lib/bullet.rb#L117-L130).

Are notifications turned on? If you turn them off, (all this code is disabled)[https://github.com/flyerhzm/bullet/blob/master/lib/bullet/rack.rb#L16-L26] and there's a lot less culprits.

I would reopen `Bullet::Rack` and start turning things on and off and watch what happens.

**Comment by flyerhzm** [comment]
I didn't see such issue, please reopen it if the issue still exists.
