### ISSUE TITLE
Attempts to read primary key on nil has_one associations

### ISSUE THREAD

**Issue by activefx** [flyerhzm/bullet#206]
I am experiencing "NoMethodError - undefined method `id' for nil:NilClass" errors, and the stacktrace reveals it is being caused by Bullet attempting to read the primary key on a nil instance of a has_one relationship. This occurs when attempting to initialize an activerecord model with a has_one relationship. 
````
  bullet (4.14.1) lib/bullet/ext/object.rb:10:in `primary_key_value'
  bullet (4.14.1) lib/bullet/detector/n_plus_one_query.rb:37:in `add_impossible_object'
  bullet (4.14.1) lib/bullet/active_record42.rb:125:in `reader'
```` 

I began encountering this error after this commit: e94c6a30a042ac69f8c0a10b6da01d4b54c6965a (with the section that seems to be causing the problem pasted below)
````
if ::ActiveRecord::Reflection::HasOneReflection === @reflection
  Bullet::Detector::NPlusOneQuery.add_impossible_object(result)
end
````

**Comment by flyerhzm** [comment]
@activefx fix in version 4.14.2

**Comment by sauy7** [comment]
I'm seeing this in version 4.14.6 running Rails 4.2.1 with polymorphic has_one associations

**Comment by tuvistavie** [comment]
Same here.

**Comment by wstrinz** [comment]
Same here, getting

```
undefined method `id' for nil:NilClass
     # /bullet-4.14.6/lib/bullet/ext/object.rb:10:in `primary_key_value'
     # /bullet-4.14.6/lib/bullet/detector/n_plus_one_query.rb:37:in `add_impossible_object'
     # /bullet-4.14.6/lib/bullet/active_record42.rb:160:in `reader'
     # /activerecord-4.2.1/lib/active_record/autosave_association.rb:302:in `validate_single_association'
```

on a has_one polymorphic association with the latest version.

**Comment by flyerhzm** [comment]
I think it's already fixed on master branch

**Comment by sauy7** [comment]
Master seems to work for my case, nice job. Thanks.
