### ISSUE TITLE
Not working with Rails 4 and Postgres?

### ISSUE THREAD

**Issue by chrismahon** [flyerhzm/bullet#207]
Hi Guys, trying to get Bullet to run on my local development but can't see anything showing up in the logs or any popups on pages. I'm running Rails 4.1.8 and Postgres for the DB, here is a sample of the code I'm using:

**Gemfile**
```
group :development do
  gem 'bullet'
end
```

**config/environments/development.rb**
```
Rails.application.configure do

    config.cache_classes = false
    config.eager_load = false
    config.consider_all_requests_local = true
    config.action_controller.perform_caching = false
    config.action_mailer.raise_delivery_errors = false
    config.active_support.deprecation = :log
    config.active_record.migration_error = :page_load
    config.assets.debug = true
    config.assets.raise_runtime_errors = true
    config.action_mailer.default_url_options = { host: 'localhost', port: 3001 }

    config.after_initialize do
        Bullet.enable = true
        Bullet.alert = true
        Bullet.bullet_logger = true
        Bullet.console = true
        Bullet.rails_logger = true
        Bullet.add_footer = true
    end

end
```

**app/models/articles.rb**
```
class Article < ActiveRecord::Base
  has_many :comments
end
```

**app/models/comments.rb**
```
class Comment < ActiveRecord::Base
  belongs_to :article
end
```

**app/views/articles/index.html.erb**
```
<% @articles.each do |article| %>
    <%= article.title %>
    <%= article.comments.map(&:name) %>
<% end %>
```

I've included the `map(&:name)`code purely to test if Bullet is working or not as this was an example in the Readme which should trigger Bullet into action, yet I'm not seeing anything. Any ideas?

**Comment by flyerhzm** [comment]
@chrismahon did you insert some data in db?

**Comment by chrismahon** [comment]
@flyerhzm thanks for the reply – was just testing this earlier and if I only have 1 article (with 2 comments) I don't get any errors. However if I have more than 2 articles (both with 2 comments) then I do get errors.

So looks like it is now working, have I misunderstood when I should be seeing errors? I was expecting to see them even with only 1 article?

Thanks again for your help.

**Comment by flyerhzm** [comment]
@chrismahon it's the limitation of bullet, it detects n+1 queries based on result, if you have only 1 article, it just sends one query for comments, so bullet doesn't treat it as n+1 query.

**Comment by chrismahon** [comment]
@flyerhzm ahhh right makes sense now, thanks for clearing that up :)
