### ISSUE TITLE
suggestion: add key combination to hide footer

### ISSUE THREAD

**Issue by ashanbrown** [flyerhzm/bullet#211]
I use rack mini profiler to see sql fetches during development and it allows you to hide it by option-p.  I'm wondering if you'd consider incorporating something similar into bullet.  Often I need to access something in the footer (particularly the switch user dropdown that I also have down there) and it gets covered by the bullet filter and I'm not sure I want whitelist to all the exceptions I see.  Sorry I don't have a pull-request ready at this time, but I could look into it.  Thanks,

Andrew

**Comment by flyerhzm** [comment]
@dontfidget I'd appreciate it if you could send me a pull request.

**Comment by flyerhzm** [comment]
@ashanbrown you can double click bullet footer layer to hide it.

**Comment by ashanbrown** [comment]
Awesome to know.  Thanks!
