### ISSUE TITLE
Live streaming does not work when bullet enabled

### ISSUE THREAD

**Issue by FlySnake** [flyerhzm/bullet#212]
When bullet is enabled live streaming feature stop working (http://stackoverflow.com/questions/28966821/rails-live-streaming-not-working-freezes-request).
See this app https://github.com/FlySnake/rails_bullet_live_streaming_issue. It's a fresh rails 4.2.0 app with live streaming (`app/controllers/lives_controller.rb`)and bullet enabled. If you run it and try to `curl -i http://localhost:3000/lives/test` it hangs, nothing will be sent back to the client, however rails says in log that all is ok.
Then try to disable bullet in `config/enviroments/development.rb`, restart, and now live streaming works.

**Comment by mattclar** [comment]
I am also having this exact problem, very frustrating! glad I found this issue, this would have stumped me for days!!

**Comment by flyerhzm** [comment]
@FlySnake @mattclar fixed on master branch

**Comment by hirosmans** [comment]
+1
i'm having the same problem using ruby 2.2.3 y rails 4.2.4
