### ISSUE TITLE
Using Bullet without Rails

### ISSUE THREAD

**Issue by ToadJamb** [flyerhzm/bullet#223]
I am attempting to use Bullet without Rails. I'm not 100% sure that I'm doing this right, but I was attempting to follow [the job profiling section of the readme](https://github.com/flyerhzm/bullet#profile-a-job):

```ruby
Bullet.profile do
  # do anything
end
warnings = Bullet.warnings
```

Upon receiving errors about `undefined method 'collection for nil:NilClass`, I dug into the Bullet code and found [this](https://github.com/flyerhzm/bullet/blob/master/lib/bullet.rb#L170) (pasted here for convenience):

```ruby
def profile
      Bullet.start_request if Bullet.enable?

      yield

      if Bullet.enable? && Bullet.notification?
        Bullet.perform_out_of_channel_notifications
      end
      Bullet.end_request if Bullet.enable?
    end
```

The interesting bit is that the thing referenced by `notification_collector` (the thing that is nil) in `warnings` is set to nil in `end_request`, but is set to a notification collector in `start_request`, so I'm unsure of how you access it after the profile block. If `enable` is true, it will be set to nil after profiling and if `enable` is false, it appears to not be set at all.

For now, I am accessing `Bullet.warning` inside the `profile` block, but I'm not sure if that's the right answer and was hoping for some guidance.

**Comment by flyerhzm** [comment]
@ToadJamb you are right, warnings are only available in profile block, I also updated README, thanks
