### ISSUE TITLE
undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by koenoe** [flyerhzm/bullet#233]
I've got a model with a belongs_to association, but when I leave it empty (NULL) Bullet throws an error:

````ruby
undefined method `id' for nil:NilClass
````

This is because of line 10 in bullet (4.14.6) lib/bullet/ext/object.rb

Which is in this method:

````ruby
def primary_key_value
    if self.class.respond_to?(:primary_key) && self.class.primary_key
      self.send self.class.primary_key
    else
      self.id
    end
end
````

I'm using ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14] and Rails 4.2.1

**Comment by flyerhzm** [comment]
@koenoe please try master branch and let me know if it fixes the problem

**Comment by StefSchenkelaars** [comment]
@flyerhzm Had the same problem, master branch fixed it.

**Comment by matthewford** [comment]
Which commit fixes the issue, I just ran into this again.

**Comment by flyerhzm** [comment]
@matthewford see https://github.com/flyerhzm/bullet/commit/e9b8dcde

**Comment by philister** [comment]
+1
