### ISSUE TITLE
Disabling Bullet for a controller action in README does not currently work

### ISSUE THREAD

**Issue by lowjoel** [flyerhzm/bullet#247]
The README says that it is possible to disable Bullet for a particular action by using this:

```ruby
class ApplicationController < ActionController::Base
  around_action :skip_bullet

  def skip_bullet
    Bullet.enable = false
    yield
  ensure
    Bullet.enable = true
  end
end
```

I've tried with Rails 4.2, and because the request starts being profiled at the Rack level, `Bullet.enable` has no effect.

**Comment by flyerhzm** [comment]
@lowjoel it should work, although default bullet is enabled at the rack level, you can still disable it in the controller level, it's a global switcher, unless bullet detects n+1 plus one query before it's disabled.

**Comment by lowjoel** [comment]
I traced into the detector, it checks `Bullet.start?`. If I set `Bullet.enable = false`, `Bullet.start?` is still true because Rack starts the trace.

**Comment by flyerhzm** [comment]
@lowjoel oh, my fault, will fix it later or you can send a pull request

**Comment by lowjoel** [comment]
so the n+1 detector is supposed to check `Bullet.enabled?` if so I'll PR that.

**Comment by flyerhzm** [comment]
@lowjoel yes, thanks.
