### ISSUE TITLE
Not support rails 5.0.0 alpha

### ISSUE THREAD

**Issue by FlowerWrong** [flyerhzm/bullet#249]
Hello! This gem does not support `rails 5.0.0 alpha`

**Comment by flyerhzm** [comment]
@FlowerWrong I'm failed to bundle install rails 5.0.0.alpha

```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (>= 0) ruby depends on
      actionpack (= 5.0.0.alpha) ruby depends on
        rack (~> 2.x) ruby
Could not find gem 'rack (~> 2.x) ruby', which is required by gem 'actionpack (= 5.0.0.alpha) ruby', in any of the sources.
```

any idea?

**Comment by FlowerWrong** [comment]
There are two ways.
One is clone the master of rails, and then use it to create the rails project. It is using rake 2.
The other is that check out the commit of rails about update to rake 2，use this commit to create rails project. It is using rake 1. You can search it in rails commit.

**Comment by flyerhzm** [comment]
rails 5 is already supported.
