### ISSUE TITLE
False positive with `has_one` relationship

### ISSUE THREAD

**Issue by mockdeep** [flyerhzm/bullet#251]
I've built a simple repro for an issue I'm seeing with bullet version `4.14.7`. Looks like a regression, since I don't see the error on `4.14.4`.

https://github.com/mockdeep/bullet_repro

**Comment by mockdeep** [comment]
In particular, see `home_controller` for the steps: https://github.com/mockdeep/bullet_repro/blob/master/app/controllers/home_controller.rb

**Comment by flyerhzm** [comment]
@mockdeep I don't get what you mean, don't you think it should add `includes`?

```
user_1, user_2 = User.all.includes(:order => :items)
```

**Comment by mockdeep** [comment]
Oh, hmm. Yeah, that makes sense. I'll have to go back and try it against the code I got this from. Closing for now.
