### ISSUE TITLE
Update Gem version

### ISSUE THREAD

**Issue by syndbg** [flyerhzm/bullet#257]
Latest Gem version in `rubygems` is `4.14.7` - May.

Please update the version to include all the latest changes including the critical compatibility fix for `composite_primary_keys`.

P.S installing gems from GitHub repos is possible, yes, but not so reliable.

**Comment by flyerhzm** [comment]
@syndbg I just released 4.14.8 (forgot to release before) and 4.14.9

**Comment by syndbg** [comment]
Thank you!
