### ISSUE TITLE
Uninitialized constant Bullet

### ISSUE THREAD

**Issue by sadiksha** [flyerhzm/bullet#262]
Hi,
I am working on Rails 4.0.0 and Ruby 2.1.2-p95, in my development section of Gemfile I added 
`gem 'bullet'`

And in the config/environments/development.rb I had the following code:
```ruby
config.after_initialize do
  Bullet.enable = true
  Bullet.alert = true
  Bullet.bullet_logger = true
  Bullet.console = true
  Bullet.rails_looger = true
end
```

I restart my server and I get `Uninitialized constant Bullet` and my development server crashes. Can you please help me with this issue?

**Comment by flyerhzm** [comment]
@sadiksha did you run `bundle install` before restarting your server? what's bullet version in your Gemfile.lock?

**Comment by sadiksha** [comment]
Thanks for your response. Yes, I did run bundle install and the version of my bullet gem is 4.14.10. Here is the complete error, if that helps.
`
/Users/Entelios/entelios/OAMP/config/environments/development.rb:74:in `block (2 levels) in <top (required)>': uninitialized constant Bullet (NameError)
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `run'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/Entelios/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/Entelios/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Entelios/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/Entelios/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/Entelios/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/Entelios/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/Entelios/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/Entelios/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/Entelios/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/application.rb:215:in `initialize!'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/Entelios/entelios/OAMP/config/environment.rb:5:in `<top (required)>'
	from /Users/Entelios/entelios/OAMP/config.ru:3:in `block in <main>'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
	from /Users/Entelios/entelios/OAMP/config.ru:in `new'
	from /Users/Entelios/entelios/OAMP/config.ru:in `<main>'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/rack-1.5.5/lib/rack/builder.rb:49:in `eval'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/rack-1.5.5/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/rack-1.5.5/lib/rack/builder.rb:40:in `parse_file'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/rack-1.5.5/lib/rack/server.rb:277:in `build_app_and_options_from_config'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/rack-1.5.5/lib/rack/server.rb:199:in `app'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/commands/server.rb:48:in `app'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/rack-1.5.5/lib/rack/server.rb:314:in `wrapped_app'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/commands/server.rb:75:in `start'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/commands.rb:78:in `block in <top (required)>'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/commands.rb:73:in `tap'
	from /Users/Entelios/.rvm/gems/ruby-2.1.2/gems/railties-4.0.0/lib/rails/commands.rb:73:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
`

**Comment by javvarcar** [comment]
Same problem here with   bullet (4.14.10)

/environments/development.rb:48:in `block (2 levels) in <top (required)>': uninitialized constant Bullet (NameError)

This is the line in development.rb

config.after_initialize do
    Bullet.enable = true
    Bullet.alert = true
    Bullet.bullet_logger = true
    Bullet.console = true
    Bullet.rails_logger = true
    Bullet.bugsnag = false
    Bullet.airbrake = false
    Bullet.add_footer = true 
  end

**Comment by matiasmasca** [comment]
I have the same issue with  bullet (5.0.0)

In my config/env.../development.rb
`config.after_initialize do
    Bullet.enable = true
    Bullet.bullet_logger = true
    if ENV['BULLET']
      Bullet.rails_logger = true
      Bullet.add_footer = true
    end
  end`

**Comment by flyerhzm** [comment]
I don't see such issue, could you give me a demo repository that I can reproduce it?

**Comment by javvarcar** [comment]
In my case I think it is a issue with my gems (in local). I downloaded again my repo and everything is working now.

**Comment by liyaodong** [comment]
same problem...

**Comment by aelor** [comment]
+1

**Comment by flyerhzm** [comment]
I created a demo app https://github.com/flyerhzm/bullet_test and I didn't see such issue, please reopen the ticket if you can reproduce it on the demo app

**Comment by fdc263** [comment]
same problem to use Bullet with Rspec...

was solved moving 

```
  if Bullet.enable?
    config.before(:each) do
      Bullet.start_request
    end

    config.after(:each) do
      Bullet.perform_out_of_channel_notifications if Bullet.notification?
      Bullet.end_request
    end
  end
```

to rspec/rails_helper.rb, inside RSpec.configure block

**Comment by arthurbryant** [comment]
**Problem**

I encountered the same problem when deploy with capistrano 3.5.0

Then I check `bundle list | grep bullet` and found it was not installed.

Then I was wondering wether capistano bundle does not install development group gems and I found this.

https://github.com/capistrano/bundler
<img width="923" alt="screen shot 2016-06-24 at 17 02 52" src="https://cloud.githubusercontent.com/assets/853200/16331803/8ae654f4-3a2d-11e6-8738-36d66d72624e.png">

**Solution**

So what I need to do is make sure capistrano install gems in development group. 

```config/deploy/development.rb
set :bundle_without, [:test]
```

Just for people who may have the same problem as me!

**Comment by flyerhzm** [comment]
@arthurbryant don't  install bullet on production env, it hurts performance a lot.

**Comment by arthurbryant** [comment]
@flyerhzm Thanks for your tip. I won't. I only use it on development env. It helps!

**Comment by flyerhzm** [comment]
@arthurbryant so it is expected that bullet is not installed on production env

**Comment by Br3nda** [comment]
I also encountered this error when adding bullet to the growstuff open source project.
I needed to move this snippet as per: https://github.com/flyerhzm/bullet/issues/262#issuecomment-225978683

Perhaps the instructions need updating?

**Comment by RafaelPrallon** [comment]
I had this issue and to solve it i've followed the solution indicated here: https://stackoverflow.com/a/50813770/8479614

**Comment by flyerhzm** [comment]
ok, I updated README to put code to `rails_helper.rb`

**Comment by boardfish** [comment]
@RafaelPrallon's solution worked for me - loading from `rails_helper.rb` still results in an error.

**Comment by saranicoly** [comment]
> @RafaelPrallon's solution worked for me - loading from `rails_helper.rb` still results in an error without it.

same here.
