### ISSUE TITLE
Bullet doesn't work with Rails 5

### ISSUE THREAD

**Issue by yoelblum** [flyerhzm/bullet#267]
Bullet doesn't support activerecord 5 beta which Rails 5 depends on. 
Some more info : 
It first fails during autoload-
 autoload :ActiveRecord, "bullet/#{active_record_version}" if active_record?
When autoloading the adapter for activerecord 4.2 you get more failures , looks like activerecord 5 has breaking changes

**Comment by dlupu** [comment]
:+1:

**Comment by ryanswood** [comment]
Bullet has become an essential part of my test suite, but will have to be removed until it is compatible with the latest and greatest AR version. Hopefully the discussion can be started on the changes to make the fix.

**Comment by ryanswood** [comment]
Excuse me for name dropping, but @pacso and @FlowerWrong have made progress on their forks with the AR 5.0 changes.

**Comment by pacso** [comment]
Haha, thanks! It needs a little work yet. New Year and my daughters 1st birthday have delayed things for the weekend.

**Comment by sxjoel** [comment]
@pacso Hi where can I take a look at your fork?

**Comment by pacso** [comment]
It's here in a branch - https://github.com/pacso/bullet/tree/rails5.0

**Comment by pacso** [comment]
I've created a pull request for this - https://github.com/flyerhzm/bullet/pull/270

Will need a review to check that all of the association specs from AR4 are appropriate for AR5

**Comment by ryanswood** [comment]
@pacso Awesome work! I am using your version on Rails 4.2.5 and will let you know if there are any problems when I successfully make the switch to Rails 5. I wish I could be of more help.

**Comment by flyerhzm** [comment]
@pacso I have already merged your pull request and publish a new release, thanks a ton.

**Comment by pacso** [comment]
@flyerhzm you're very welcome. Glad I could give a little back :)

**Comment by FlowerWrong** [comment]
:8ball:
