### ISSUE TITLE
N + 1 and Unused Eager Loading Variation

### ISSUE THREAD

**Issue by wbotelhos** [flyerhzm/bullet#269]
Exemplo:

I have three users. The first has a `address` the second one no.

1. If I include the address, on the second interaction will raise `Unused Eager Loading detected`.

```ruby
User.joins(:address).all.each do |user|
  user.address
end
```

2. If I do not include the address, on the first interaction will raise `N+1 Query detected` 

```ruby
User.all.each do |user|
  user.address
end
```

What can I do on this situation?
On a `has_many` relation, I can use `exists?`, but it generates another query e the code becomes bigger.
On a `belongs_to` there is no way to do that, because the record can have the relation or not.

**Comment by ID25** [comment]
+ 1, same question.

**Comment by flyerhzm** [comment]
@wbotelhos I tried latest bullet version, it's won't raise `Unused Eager Loading detected` in first case.
