### ISSUE TITLE
False N+1 Query report when used with counter_cache

### ISSUE THREAD

**Issue by octavpo** [flyerhzm/bullet#273]
If I have a counter_cache on the association and I used model.association.size, it works fine. However if I use model.association.empty? it reports an N+1 Query, even if there's no additional query since empty? knows to use the counter.

**Comment by januszm** [comment]
Well I get several false alerts about unused eager load in Rails 5 RC1 app and I do not get alerts when N+1 queries occur.

Ironically everything works fine and is optimized, ie. I get just one query per table, using where (id IN [1,2,3,4...). Bullet complains that this is unused optimization and unnecessary. But when I remove ```preload``` then I obviously get the N+1 queries.

**Comment by flyerhzm** [comment]
@januszm your problem is not related to this issue, please create a new one and give me more description.
