### ISSUE TITLE
Bullet 5.0.0 #find with ActiveRecord 4.2.0 returns error if missing :ids

### ISSUE THREAD

**Issue by jstirnaman** [flyerhzm/bullet#277]
With Rails 4.2, in bullet-5.0.0/lib/bullet/active_record42.rb:9, #find does not have the same (albeit deprecated?) behavior as activerecord-4.2.0/lib/active_record/core.rb.
In ActiveRecord 4.2:
`Model.find do...end` still behaves like `Model.all.find do...end` when `.find()` is called without `:ids`.
Using Bullet:
 `.find()` returns an error if missing `:ids`.

However, using `find` like this or `find(:all)` seems to be discouraged in AR 4.2.0.

**Comment by flyerhzm** [comment]
@jstirnaman I couldn't reproduce it, bullet-5.0.0/lib/bullet/active_record42.rb:9 is to call origin find with same arguments, it shouldn't raise such error
