### ISSUE TITLE
You must install the ruby-growl or the ruby_gntp gem to use Growl notification

### ISSUE THREAD

**Issue by acandael** [flyerhzm/bullet#282]
Hi, added bullet 5.0.0 to my Gemfile and run 'bundle install'. But when I start the local webserver (Webrick), I'm getting this error message:

    Exiting
    /Users/acandael/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/uniform_notifier-    1.9.0/lib/uniform_notifier/growl.rb:16:in `rescue in rescue in setup_connection': You must install the ruby-    growl or the ruby_gntp gem to use Growl notification: `gem install ruby-growl` or `gem install ruby_gntp`     (UniformNotifier::NotificationError)

Does anyone else encounter this?

Thanks for your help,

Anthony

**Comment by acandael** [comment]
it's fixed now. The problem was caused because I copied all the configuration settings to config/environments/development.rb

Now I'm just using:

    Bullet.enable = true
    Bullet.alert = true
    Bullet_bullet_logger = true
    Bullet.console = true

and everything works fine.

**Comment by fifiteen82726** [comment]
@acandael It's `Bullet.bullet_logger = true` instead of `Bullet_bullet_logger = true`

**Comment by jmcbri** [comment]
Well, I guess fixes the issue, but fixes it by removing the functionality, not by fixing the functionality, right?
