### ISSUE TITLE
Please replace deprecated alias_method_chain

### ISSUE THREAD

**Issue by dankohn** [flyerhzm/bullet#286]
When running off of the current HEAD of master, I get:
```bash
rails test test/controllers/projects_controller_test.rb 
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in enable at /Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/bullet-0a1db3529086/lib/bullet/active_record5.rb:31)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in enable at /Users/dan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/bullet-0a1db3529086/lib/bullet/active_record5.rb:39)
Running via Spring preloader in process 12516
```
This is mentioned on the PR https://github.com/flyerhzm/bullet/pull/278#issuecomment-189972035 that removed other uses. Could you please remove the last uses of `alias_method_chain` so as to avoid spurious errors.

Directions for using prepend are at http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/ but I'm not clear enough about how https://github.com/flyerhzm/bullet/blob/master/lib/bullet/active_record5.rb#L31-L39 works to make the PR myself.

Thanks very much.

Cc @danp60 @flyerhzm @david-c-wheeler

**Comment by flyerhzm** [comment]
@dankohn I have fixed the deprecation for active record 5
