### ISSUE TITLE
Rake task wtih N+1 queries

### ISSUE THREAD

**Issue by junaid-malik-confiz** [flyerhzm/bullet#290]
Hello,

We have lot of rake tasks in our project and we want to identify all which have n+1 queries. I tried the 'Bullet.profile' block option but it didn't work. How can i enable this gem for rake tasks? Thanks

Regard,
Junaid

**Comment by flyerhzm** [comment]
@junaid-malik-confiz does it work in normal web requests?

**Comment by junaid-malik-confiz** [comment]
yes it is working fine for normal web requests.

**Comment by flyerhzm** [comment]
@junaid-malik-confiz I added a rake task in https://github.com/flyerhzm/bullet_test and rake task works well with bullet

**Comment by junaid-malik-confiz** [comment]
Thank flyerhzm, now it is working. Before there was configuration issue.
