### ISSUE TITLE
False alerts on Rails 5 RC1 and when using Rolify gem

### ISSUE THREAD

**Issue by januszm** [flyerhzm/bullet#291]
# Bullet version <= 5.1

I use this gem to 'rolify' a User model (technically it adds HABTM association between User and Role models): https://github.com/RolifyCommunity/rolify

When I load users and preload their roles:

```ruby
  User.preload(:roles)...
```

I see the alert:

```
Unused Eager Loading detected
  User => [:users_roles]
  Remove from your finder: :includes =>  #[:users_roles]
```

This is clearly a false alert because the code above ( ```.preload``` ) triggers those queries:

```sql
  User Load (0.3ms)  SELECT  "users".* FROM "users"
  HABTM_Roles Load (0.4ms)  SELECT "users_roles".* FROM "users_roles" WHERE "users_roles"."user_id" IN (27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51)
  Role Load (0.5ms)  SELECT "roles".* FROM "roles" WHERE "roles"."id" IN (28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52)
```

But when I remove ```.preload``` from my finder, I don't see the alert but I clearly have N+1 query problem:

```sql
  User Load (0.3ms)  SELECT  "users".* FROM "users"
  HABTM_Roles Load (0.4ms)  SELECT "users_roles".* FROM "users_roles" WHERE "users_roles"."user_id" IN (27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51)
  Role Load (0.2ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1  [["user_id", 27]]
  Role Load (0.3ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1  [["user_id", 28]]
  Role Load (0.2ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1  [["user_id", 29]]
  Role Load (0.2ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1  [["user_id", 30]]
  ...
```

**Comment by h8rry** [comment]
I have the same issue in Rails 5.0

**Comment by flyerhzm** [comment]
@januszm what if you replace `preload` with `includes`?

**Comment by h8rry** [comment]
@flyerhzm I tried with both `.include` and `ActiveRecord::Associations::Preloader`. Same error.

**Comment by flyerhzm** [comment]
@h8rry could you build a demo repo to reproduce this issue?

**Comment by januszm** [comment]
@flyerhzm It doesn't make any difference if I change it from ```preload``` to ```includes```. It looks like I always get the opposite alert, when queries are OK, I get warning ```Unused Eager Loading detected```. When I remove preloading, I get N+1 queries obviously.

**Comment by flyerhzm** [comment]
@januszm @h8rry I do have tested has_and_belongs_to_many https://github.com/flyerhzm/bullet/blob/master/spec/integration/active_record5/association_spec.rb#L431, any difference can you figure out?

**Comment by januszm** [comment]
@flyerhzm In my app it's about

```ruby
class User < ApplicationRecord
  rolify # this adds user has_and_belongs_to_many roles association

  has_many :company_users
  has_many :companies, through: :company_users
```

```ruby
class Site < ApplicationRecord
  belongs_to :company
```

and query like

```site.preload(company: { users: :roles })```

**Comment by h8rry** [comment]
@flyerhzm I made a demo app. It now has a different issue, where it's not showing N+1 errors. See https://github.com/h8rry/bullet-demo/blob/master/spec/controllers/users_controller_spec.rb

**Comment by flyerhzm** [comment]
@h8rry you must create AR objects before bullet start_request, see

```
index 1ccca37..abb89e9 100644
--- a/spec/controllers/users_controller_spec.rb
+++ b/spec/controllers/users_controller_spec.rb
@@ -4,6 +4,14 @@ RSpec.describe UsersController, type: :controller do
   render_views

   before(:each) do
+    @user_1 = User.create
+    @user_2 = User.create
+
+    20.times do
+      Question.create(title: 'random', user: @user_1)
+      Question.create(title: 'random', user: @user_2)
+    end
+
     Bullet.start_request
   end

@@ -14,19 +22,11 @@ RSpec.describe UsersController, type: :controller do

   context "index all users, includes each user's questions" do
     it "responds correctly" do
-      user_1 = User.create
-      user_2 = User.create
-
-      20.times do
-        Question.create(title: 'random', user: user_1)
-        Question.create(title: 'random', user: user_2)
-      end
-
       expected_response = {
         users: [{
-          questions: user_1.questions
+          questions: @user_1.questions
         }, {
-          questions: user_2.questions
+          questions: @user_2.questions
         }]
       }
```

because of #278

**Comment by januszm** [comment]
@flyerhzm It's actually much better after I upgraded bullet from 5.1 to 5.2.

And it's all fine if I use version from Github! You've fixed something on master since 5.2 ?

**Comment by januszm** [comment]
@flyerhzm I'm closing it. Your last two commits resolved the issue

**Comment by januszm** [comment]
@flyerhzm please release version 5.2.1 that contains those last fixes

**Comment by h8rry** [comment]
@flyerhzm Thanks for pointing that out. I didn't know that. It works now with AR, but not `find_by_sql`. Please see #303.

**Comment by flyerhzm** [comment]
@januszm version 5.2.1 is released, thanks

**Comment by edwardmp** [comment]
@flyerhzm are you sure this is solved? Using 5.5.1 I can still reproduce this exact issue.

**Comment by flyerhzm** [comment]
@edwardmp if it's not, could you show me an example?

**Comment by edwardmp** [comment]
@flyerhzm what kind of example do you want? Queries that are generated, an example app showing this behavior..?

By the way, this gem currently does not really produce any sensible warnings at all. The avoid eager load is triggered for associations that are clearly accessed in a loop on a page. Also, does this warning still trigger when preloading is actually used (whether automatically or explicitly)?

**Comment by KevinSchiffmann** [comment]
Hello,

We are not using Rolify, but we have the same HABTM structure ("User" HABTM "Role")

- Without includes(:roles), I get an N+1 when calling user.role_ids inside my loop.
- With includes(:roles), I don't have N+1, but I have a bullet warning telling me I should remove eager loading.

I think it's linked to the Rails "_ids" method. If I replace it by something like "user.roles.map(&:id)", there's no warning anymore.

I'm using Rails 5.1.5 and bullet 5.7.5. Let me know if you need more details.

Thank you very much :)
