### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by yknx4** [flyerhzm/bullet#293]
Is not really clear how to configure the slack integration besides the `webhook_url`

`Bullet.slack = { webhook_url: 'http://some.slack.url', foo: 'bar' }`

Like what does `foo: 'bar'`stands for in this example, i know it is usually left as placeholder. But in this case what could go in there?

**Comment by flyerhzm** [comment]
@yknx4 I updated README for slack notifier, you can check out more here, https://github.com/stevenosloan/slack-notifier
