### ISSUE TITLE
disable + enable should not clear whitelists

### ISSUE THREAD

**Issue by nathanl** [flyerhzm/bullet#295]
First off: thanks for making Bullet! The issue I'm having is more the fault of my legacy app than of Bullet, so feel free to close this if you don't feel like dealing with it. If nothing else, it might be useful for others having a similar problem to find this thread.

From the README:

```ruby
def skip_bullet
    Bullet.enable = false
    yield
  ensure
    Bullet.enable = true
 end
```

When Bullet is enabled again, it will [reset all whitelists](https://github.com/flyerhzm/bullet/blob/75ba0171cafbe64f6abb8ab7191cca5aac16fbf9/lib/bullet.rb#L47-L50). This seems wrong.

My actual use case is that I want to "pause" Bullet for a specific test. I have an integration spec for a controller action, and also a controller test for that action. The integration spec renders the views and uses an association, but the controller spec requests JSON and doesn't use the association. So if I don't eager load it in the controller, I get an N+1 exception from the test that uses the view, but if I do, I get an used eager loading exception from the test that doesn't use the view.

What I want is to just skip bullet on the controller test, via a tag:

```ruby
  # in test file
    it "gets the JSON", :skip_bullet do
      # ..
    end

  # in spec_helper.rb
  # Bullet false alarms on some specs, so here's a way to disable it via tags
  config.before(:each, :skip_bullet) do
    @bullet_enabled_before_test = Bullet.enable?
    Bullet.enable = false
  end
  config.after(:each, :skip_bullet) do
    Bullet.enable = @bullet_enabled_before_test
  end
```

But because I have some whitelists settings that get cleared, using the tag on one test makes a bunch of others fail.

In my case I'd probably be best off to delete all the whitelist settings, fix any query problems I can, and use `:skip_bullet` on the rest of the tests. But this is a legacy app and that will take time.

In the meantime, it would be nice to be able to `Bullet.pause` without losing whitelists.

**Comment by flyerhzm** [comment]
@nathanl I don't think whitelist will be truly reset, https://github.com/flyerhzm/bullet/blob/75ba0171cafbe64f6abb8ab7191cca5aac16fbf9/lib/bullet.rb#L93-L95, reset_whitelist only reset the whitelist when it is nil.

**Comment by nathanl** [comment]
@flyerhzm Hmm. What you say looks correct, but in my application, I have a passing test suite with some whitelist rules. If I add the following two lines after my `Bullet.add_whitelist` declarations:

    Bullet.enable = false
    Bullet.enable = true

... I get a lot of new test failures, all of them from Bullet exceptions (using `Bullet.raise = true`).

Will try to see if I can make a failing test case or otherwise pinpoint the problem.

**Comment by nathanl** [comment]
@flyerhzm You were correct - the problem was that I was using a version from before [this commit](https://github.com/flyerhzm/bullet/commit/c88ac323884088fa10733103ba248b50010a4211).

Sorry to bother you!

**Comment by ezekg** [comment]
I was able to get around this rather confusing issue by doing the following:

```rb
Bullet.instance_variable_set :@enable, false
…
Bullet.instance_variable_set :@enable, true
```

I don't think it makes sense to reset everything when `enabled` is toggled.
