### ISSUE TITLE
Unused Eager Loading false positive on `has_many :through` relationship

### ISSUE THREAD

**Issue by mockdeep** [flyerhzm/bullet#301]
I have a basic repro for an issue I'm seeing that looks to be a false positive on `has_many :through` relationships. It's on my [repo here](https://github.com/mockdeep/bullet_repro), the [commit here](https://github.com/mockdeep/bullet_repro/commit/b0f248aee064b612aa11577e61173b37a45de871) is a more focused look at the repro. You can run `rake db:setup` and then visit `/items` on localhost and it should show an error. The issue was introduced when I upgraded bullet on one of my projects from version `4.14.4` to `5.2.0`.

**Comment by mockdeep** [comment]
Looks like it was introduced in version `5.1`, as I was able to upgrade to `5.0.0` without issue.

**Comment by flyerhzm** [comment]
@mockdeep thanks for reporting the issue and making a demo repo, I should have fixed it, please try master branch and let me know if it's working for you.

**Comment by mockdeep** [comment]
@flyerhzm yep, looks like that did the trick.

**Comment by mockdeep** [comment]
@flyerhzm this seems to re-introduce another false positive. It looks related to #203 #201 and the issue I reported in #251 (but didn't come up with a good repro for...). Spent some time trying to lock down a clean repro but didn't figure it out just yet.
