### ISSUE TITLE
Does bullet not catch unoptimized queries from find_by_sql?

### ISSUE THREAD

**Issue by h8rry** [flyerhzm/bullet#303]
Bullet doesn't seem to detect n+1 queries from `.find_by_sql`. Is it because `.find_by_sql` returns an array instead of AR?

User.find_by_sql: https://github.com/h8rry/bullet-demo/blob/master/app/controllers/users_controller.rb
Specs: https://github.com/h8rry/bullet-demo/blob/master/spec/controllers/users_controller_spec.rb

In this case, bullet should raise errors since no eager loading was made.

**Comment by flyerhzm** [comment]
@h8rry you test is wrong, check my comment in #291

**Comment by h8rry** [comment]
My previous spec should do the same as your suggestion. However, I have changed it to your expressions: https://github.com/h8rry/bullet-demo/blob/master/spec/controllers/users_controller_spec.rb

It's still not showing n+1 queries.

**Comment by flyerhzm** [comment]
@h8rry please try the master branch.

**Comment by h8rry** [comment]
@flyerhzm thanks for the quick response and code patch! It works for me with Rails 5.0.
