### ISSUE TITLE
Display HTTP methods that used on the resource

### ISSUE THREAD

**Issue by azbshiri** [flyerhzm/bullet#311]
Hey, is it possible to display the method that's been used on the resource? 

### Actual behaviour
user: foo
/api/v1/users
N+1 Query detected
  User => [:blog]
  Add to your finder: :includes => [:blog]
N+1 Query method call stack
### Expected behaviour
user: foo
GET /api/v1/users
N+1 Query detected
  User => [:blog]
  Add to your finder: :includes => [:blog]
N+1 Query method call stack

**Comment by flyerhzm** [comment]
@azbshiri fixed and bumped version 5.4.1

**Comment by azbshiri** [comment]
I switched to the new version but HTTP method still is not shown.

**Comment by flyerhzm** [comment]
@azbshiri does not test properly, have released a new one to fix this.
