### ISSUE TITLE
Bullet.profile best practices?

### ISSUE THREAD

**Issue by benjamin-thomas** [flyerhzm/bullet#313]
Hi,

I'd like to use Bullet to help me catch n+1 queries when designing complex background tasks.

Usually, my workflow consists of iterating on a given method several times in development, with synced production data (I'm spiking a lot at this point).

This is where I introduce n+1 queries (due to complex business logic).

Since those background tasks won't be used within the cycle of an HTTP request, `Bullet.profile` seems perfect for my needs.

Ideally, I'd like to noop in production while guarding against future errors in dev and test environments.

I thought about creating a custom wrapper for problematic methods.

```ruby
  def self.prevent_n_plus_one_queries
    if Rails.env.development? || Rails.env.test?
      return Bullet.profile { yield }
    end

    yield
  end

  def self.my_complex_background_task_method
    prevent_n_plus_one_queries do
      complex_business_logic
    end
  end
```

I'd like some input on that idea, possibly updating the README?

Also I'm wondering: if one of those methods does get used later on within the cycle of an HTTP request, would this have any problematic side effects (multiple profile calls)?

Thanks for your feedback.

**Comment by flyerhzm** [comment]
@benjamin-thomas you don't need to check `Rails.env.development?` or `Rails.env.test?`, in `Bullet.profile`, it only takes effect if Bullet is enabled, otherwise, it just runs yield, so you can use `Bullet.profile` directly instead of using `prevent_n_plus_one_queries` method.

You can call `Bullet.profile` as many times as you like, there's no side effect.

**Comment by benjamin-thomas** [comment]
Got you.

Although Bullet won't be loaded in production since it's scoped to the development group in my Gemfile, so I get a `NameError` that way.

I assume you would load the gem globally? Won't that have any unwanted side effects for production?

**Comment by flyerhzm** [comment]
it will introduce too many objects to AR to help detect N+1 queries, which hurt performance a lot, that's why I don't suggest using it in production.

**Comment by benjamin-thomas** [comment]
OK, thanks for the feedback!
