### ISSUE TITLE
False positives when using responders

### ISSUE THREAD

**Issue by Quintasan** [flyerhzm/bullet#315]
Here's my controller using `decent_exposure` gem.
```ruby
class OffersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  expose :offers, ->{ Offer.all }
  expose :offer, find: ->(id, scope){ scope.includes(:user).find(id) }

  def show
  end
end
```

When I do `GET /offers/1` I get normal reponse but when I do `GET /offers/1.json`  (ie. I want to get a JSON instead of HTML) I have Bullet complaining about unused eager loading. I'm pretty much sure it shouldn't work that way. The application is available [here](https://github.com/Quintasan/herpderp). Be sure to remove the unused eager loading silencer in `config/environments/development.rb`

**Comment by flyerhzm** [comment]
@Quintasan this is because it loads offer.user in html response, but not in json response.
