### ISSUE TITLE
rack send_file not working with the bullet gem

### ISSUE THREAD

**Issue by basex** [flyerhzm/bullet#319]
When doing a send_file in a controller, I'm getting the following error:
`undefined method first for #<Rack::File:0x007ff3e99086e0>`

On the trace I get:
> .rvm/gems/ruby-2.3.0/gems/bullet-5.4.3/lib/bullet/rack.rb in response_body
> line 73: response.first

**Comment by flyerhzm** [comment]
@basex we have a method to check if it is a rack file, in `lib/bullet/rack.rb#58`, isn't it working?

**Comment by basex** [comment]
It isn't working. `file?` returns false and then it's failing on the `empty?` method.

**Comment by flyerhzm** [comment]
@basex added
