### ISSUE TITLE
Rails 5 has_one :through false positive avoid eager loading

### ISSUE THREAD

**Issue by naw** [flyerhzm/bullet#323]
When you `preload` a `has_one :through` association, Rails loads the intermediate association followed by the source association.

Rails 5 [changed how the intermediate results are accessed](https://github.com/rails/rails/commit/842f5c2dad8ed021274c16f2dc231c15ddefba18) during preloading such that `#reader` is bypassed. As a result, Bullet is unaware that these associations have been accessed (i.e. `Bullet::Detector::NPlusOneQuery.call_association` isn't called).

This results in false positive avoid eager loading warnings from the model to the intermediate association as well as from the intermediate association to the source association.

As an example, if you have the following models:

```ruby
class City < ActiveRecord::Base
  belongs_to :country
  has_one :continent, through: :country
end

class Country < ActiveRecord::Base
  belongs_to :continent
end

class Continent < ActiveRecord::Base
end
```

Then, the following code will cause Bullet to emit two incorrect avoid eager loading warnings:

`City.preload(:continent).map(&:continent)`

```
AVOID eager loading detected
  City => [:country]
  Remove from your finder: :includes => [:country]

AVOID eager loading detected
  Country => [:continent]
  Remove from your finder: :includes => [:continent]
```

My first thought is [hooking into `target` instead of `reader`](https://github.com/naw/bullet/commit/a325ef619530924df8d52096b7a44b8dc0d3f7b6) would fix this issue, but I'm not super-familiar with Bullet, so I'm not sure what unintended consequences that might have.

**Comment by CodingAnarchy** [comment]
Can we get a gem release with this fix included?  I didn't realize I needed to switch to the `master` branch to fix this problem and it took up a few hours of my time.  I'm sure it is affecting others.

**Comment by CodingAnarchy** [comment]
Actually, it doesn't seem to be fixed in `master` either - I'm still seeing the error.

**Comment by KenneyE** [comment]
I'm also still seeing this issue, both on the published gem and on master...

**Comment by okolomoets** [comment]
I still have this issue. 
Can you please tell me if it's fixed in some special version?

My current version of the `bullet` gem is `6.0.2`.

**Comment by georgewambold** [comment]
I'm still having this issue -- Bullet complains about unused eager loading of a through association, but when I get rid of `:includes` it complains that I should be using eager loading.

**Comment by dmarczal** [comment]
Same problem here, any solution?

**Comment by iqbalhasnan** [comment]
hey, I'm having the same issue. how are we supposed to handle the conditional includes?

**Comment by shavin-peiries** [comment]
Hey, I'm having this issue too! How did you handle it?
