### ISSUE TITLE
Would you recommend using bullet in production?

### ISSUE THREAD

**Issue by fatuhoku** [flyerhzm/bullet#328]
Useful for fast debugging if it's able to tell us where exactly the offending line of code lives.

**Comment by flyerhzm** [comment]
@fatuhoku I don't recommend, bullet will make your app much slower on production.

**Comment by kbacha** [comment]
@flyerhzm I noticed this was from 2 years ago, is the recommendation the same?

**Comment by flyerhzm** [comment]
@kbacha no, it's still not recommended.

**Comment by mathieujobin** [comment]
I am also curious about this.
I'd like to have it disabled by default, but able to enable it for a certain time window, or for a single request via query parameter.

I wanted to take a database dump and attempt to reproduce locally, but the DB is too large
