### ISSUE TITLE
No call stack

### ISSUE THREAD

**Issue by mandysimon88** [flyerhzm/bullet#337]
I get the following alert, which unfortunately does not include the call stack:

![screen shot 2017-05-15 at 8 08 17 pm](https://cloud.githubusercontent.com/assets/12855692/26084479/54914a9e-39aa-11e7-93ab-17722ee9a8da.png)

Why does it include the call stack? How can I get it to include the call stack?
Other alerts for the same page included the stack.

**Comment by flyerhzm** [comment]
@mandysimon88 sorry, bullet doesn't support to show call stack for "AVOID eager loading detected" yet.
