### ISSUE TITLE
Update uniform_notifier dependency to support Sentry notification

### ISSUE THREAD

**Issue by nicolas-besnard** [flyerhzm/bullet#366]
When https://github.com/flyerhzm/uniform_notifier/pull/35 is merged and a new version is released

**Comment by YorickPeterse** [comment]
What is the status of this? At GitLab we would like to use Bullet combined with Sentry to track N+1 query problems and the likes in Sentry, so we'd love for this feature to become available :smile:

**Comment by flyerhzm** [comment]
@YorickPeterse I have merged it to master branch, will try to bump a new release in a few days.

**Comment by YorickPeterse** [comment]
@flyerhzm Thanks! :+1: :tada:

**Comment by flyerhzm** [comment]
fyi, I have just released version `5.7.1`

**Comment by YorickPeterse** [comment]
@flyerhzm Awesome, thanks a lot!
