### ISSUE TITLE
undefined method `include?' for #<Thread::Backtrace::Location:0x007f81e25c7338>

### ISSUE THREAD

**Issue by akkee** [flyerhzm/bullet#370]
Ruby: `2.4.0`
Rails: `5.1.4`
Bullet: `5.6.1`

This happens for a normal `belongs_to` clause, when I open this view while using `bullet`

```
ActionView::Template::Error (undefined method `include?' for #<Thread::Backtrace::Location:0x007ffb6901ac90>):
12:34:50 web.1     |     1: <div class="panel panel-default" style="margin-top: 15px;">
12:34:50 web.1     |     2:     <div class="panel-heading"><h3>Recent and Upcoming Events</h3>
12:34:50 web.1     |     3:         <h4> <%= @user_events.present? ? (link_to "Code Execution Enviroment details are here",judge_environment_static_index_path(company_logo: @user_events.first.event.company.image),:target => "_blank") : '' %> </h4>
12:34:50 web.1     |     4:     </div>
12:34:50 web.1     |     5:
12:34:50 web.1     |     6: 		<table class="table table-bordered">
12:34:50 web.1     |
12:34:50 web.1     | app/views/users/dashboard.html.erb:3:in `_app_views_users_dashboard_html_erb___512062888033679236_70358856588940'
```

https://github.com/flyerhzm/bullet/issues/347 discussion shows it to have been fixed in `5.6.1` but it seems to come up for me.

**Comment by cySheng** [comment]
Hi @akkee am wondering how did you manage to solve this error?
I seem to be having the exact same error with similar gem versions.

**Comment by obromios** [comment]
I am having the same trouble with 5.7.1. Unfortunately it makes bullet unusable for me. The exception is raised when updating a field in a model. If I take bullet out, the update works fine.

**Comment by flyerhzm** [comment]
@meacuna @cySheng @obromios I have fixed on master branch, please give it a try.

**Comment by meacuna** [comment]
@flyerhzm Seems to be working for me.
Thanks!

**Comment by mikelikesbikes** [comment]
@flyerhzm confirmed this is also working for me. :)

**Comment by obromios** [comment]
+1

**Comment by cySheng** [comment]
+1
