### ISSUE TITLE
Rails 5.1.5 + bullet error for sort on assocation

### ISSUE THREAD

**Issue by memoht** [flyerhzm/bullet#389]
I was upgrading to Rails 5.1.5 tonight and ran into a view with `Wrong number of arguments (given 1, expected 2)` error. 

+ In my controller I had the following `@adverts = @manifest.adverts.includes(:company, :product).order(:sls_rep, "companies.name")`
+ Removing .order for the `"companifes.name"`association made the error go away.

It seems that Bullet is the culprit. After removing the gem, the view rendered normally.
<img width="1280" alt="screen shot 2018-02-14 at 11 38 04 pm" src="https://user-images.githubusercontent.com/492691/36241034-c64457ca-11e1-11e8-9993-49dbdddef13c.png">

**Comment by flyerhzm** [comment]
@memoht it should be fixed by https://github.com/flyerhzm/bullet/pull/388
