### ISSUE TITLE
Error with wrong #instantiate method signature in Rails 5.1.5 (active_record5.rb).

### ISSUE THREAD

**Issue by bkuhlmann** [flyerhzm/bullet#390]
## Overview

Upgrading to Rails 5.1.5 causes Bullet to stack dump on table joins.

## Steps to Recreate

0. Upgrade to Rails 5.1.5.
0. Best I can tell, you need to build a relation that looks a bit like this (pseudo code): `Example.includes(:example_association).where(example_association: {foreign_key: foreign_key})`

<details>
  <summary>Stack Dump</summary>

```
      ArgumentError:
        wrong number of arguments (given 1, expected 2)
      # /Users/bkuhlmann/.gem/ruby/2.5.0/gems/bullet-5.7.2/lib/bullet/active_record5.rb:96:in `instantiate'
      # /Users/bkuhlmann/.gem/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/relation.rb:674:in `block in exec_queries'
      # /Users/bkuhlmann/.gem/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/relation/finder_methods.rb:374:in `find_with_associations'
      # /Users/bkuhlmann/.gem/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/relation.rb:669:in `exec_queries'
      # /Users/bkuhlmann/.gem/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/relation.rb:546:in `load'
      # /Users/bkuhlmann/.gem/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/relation.rb:255:in `records'
      # /Users/bkuhlmann/.gem/ruby/2.5.0/gems/bullet-5.7.2/lib/bullet/active_record5.rb:48:in `records'
      # /Users/bkuhlmann/.gem/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `to_ary'
```
</details>

## Notes

The issue is identifiable by comparing the ActiveRecord `JoinDependency` class. You can see the `#instantiate` method signature differs between Rails 5.1.4 and 5.1.5. Here are the source code links:

- [Rails 5.1.4](https://github.com/rails/rails/blob/9d112c2527ab50c519fdaf21a8d432b5ca18bc85/activerecord/lib/active_record/associations/join_dependency.rb#L137-L144)
- [Rails 5.1.5](https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/associations/join_dependency.rb#L137-L144)

## Environment

- Ruby 2.5.0
- Rails 5.1.5
- Bullet 5.7.2

**Comment by turboladen** [comment]
I just upgraded to rails 5.1.5 from 5.1.4 and am seeing this now too (bullet 3.7.2).

**Comment by flyerhzm** [comment]
@bkuhlmann @turboladen please try bullet 5.7.3

**Comment by bkuhlmann** [comment]
@flyerhzm Confirmed, fix works. Thanks!

**Comment by turboladen** [comment]
@flyerhzm good for me too!
