### ISSUE TITLE
Gem Load Error is: Bullet does not support active_record ActiveRecord::VERSION yet

### ISSUE THREAD

**Issue by testhackings** [flyerhzm/bullet#405]
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'bullet'.
Gem Load Error is: Bullet does not support active_record ActiveRecord::VERSION yet

ruby 2.2.3p173
Rails 3.2.22.5
bullet (5.7.5)
activerecord (3.2.22.5)

what i missed?

**Comment by flyerhzm** [comment]
If you use activerecord 3.x, please use bullet < 5.5.0

**Comment by testhackings** [comment]
It's working now. Thanks
