### ISSUE TITLE
Can't get logs into bullet.log in non-development environment

### ISSUE THREAD

**Issue by natefaerber** [flyerhzm/bullet#419]
Hi,

We are having a heck of a problem getting bullet to log to bullet.log in our non-development environments.  Developers get the logs in their environments with:

```ruby
Rails.application.configure do
[...]
  config.after_initialize do
    # https://github.com/flyerhzm/bullet
    Bullet.enable = true
    Bullet.bullet_logger = true
    Bullet.rails_logger = true
  end
end
```

But when we put the same code in environments/production.rb (manually) in a specific environment, we get some messages in stdout but nothing in bullet.log.  We are using Unicorn to run this instance of Rails but even when running `rails server`, we don't get info in bullet.log

What are we missing?

**Comment by flyerhzm** [comment]
@natefaerber did you `bullet.log` in development environment?

**Comment by natefaerber** [comment]
@flyerhzm , bullet.log gets the info we expect in our development environment.  I wonder what information I can give to help understand this.  We will hack away at it a little more today.

**Comment by natefaerber** [comment]
This was 100% our fault.  I assumed we were using the latest version of the gem but we weren't.  After upgrading from 5.6.1 to 5.7.5, we get logs.  Sorry for the noise.
