### ISSUE TITLE
Maximum call stack exceeded with Turbolinks in 6.0.0

### ISSUE THREAD

**Issue by tomca32** [flyerhzm/bullet#454]
I'm running a Rails app with Turbolinks and Bullet. Since the `6.0.0` update, I'm getting this error int the browser, after a couple of Turbolinks navigations.

```
Uncaught RangeError: Maximum call stack size exceeded
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:15:21)
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:53:33)
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:53:33)
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:53:33)
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:53:33)
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:53:33)
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:53:33)
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:53:33)
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:53:33)
    at XMLHttpRequest.newOnload [as _storedOnload] (<anonymous>:53:33)
```

It doesn't happen until the 2nd Turbolinks navigation.

**Comment by ro-savage** [comment]
We get exactly the same issue.

Configuation is:

```
    Bullet.enable = true
    Bullet.bullet_logger = true
    Bullet.console = true
    Bullet.rails_logger = true
    Bullet.add_footer = false
```

**Comment by lordofthedanse** [comment]
Oh yeah, just started getting this myself.
```
Bullet.enable = true
Bullet.alert = false
Bullet.bullet_logger = false
Bullet.console = true
Bullet.rails_logger = false
Bullet.add_footer = true
```

**Comment by artemave** [comment]
Stacktrace points to the Bullet javascript:

![image](https://user-images.githubusercontent.com/23721/57088338-61d19c80-6d02-11e9-841f-2ef08c9f065c.png)

![image](https://user-images.githubusercontent.com/23721/57088380-757d0300-6d02-11e9-8962-d11d2d03237b.png)

**Comment by teeparham** [comment]
Also happens with rails 5.2.

**Comment by andreaslillebo** [comment]
Can confirm that this also happens on rails 5.2.3 with the following config:

````ruby
config.after_initialize do
  Bullet.enable = true
  Bullet.console = true
end
````
Even with `Bullet.console = false`, I still get the error.

**Comment by hungmi** [comment]
Also happens with rails 6.0.0.rc1
```ruby
gem 'rails', '~> 6.0.0.rc1'
gem 'bullet', '6.0.0'
```

```ruby
config.after_initialize do
  Bullet.enable = true
end
```

**Comment by brian-kephart** [comment]
I'm seeing this on Rails 5.2.3 / Bullet 6.0.0 as well.

**Comment by awadhwana** [comment]
Same issue with the following configuration 

Rails 5.2.3 & Bullet (6.0.0)
turbolinks (5.2.0)

`config.after_initialize do
  Bullet.enable = true
  Bullet.console = true
end`

**Comment by janklimo** [comment]
This is an issue with any version of Turbolinks and Rails + Bullet 6. Opened #465 to resolve it.
