### ISSUE TITLE
Bullet does not support active_record 6.1.0.alpha yet

### ISSUE THREAD

**Issue by reckerswartz** [flyerhzm/bullet#457]
using rails master
rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'bullet'.
Gem Load Error is: Bullet does not support active_record 6.1.0.alpha yet

**Comment by olleolleolle** [comment]
@reckerswartz Can this be closed now that the PR is merged?

**Comment by reckerswartz** [comment]
@olleolleolle I am closing now as rails 6 is released.
