### ISSUE TITLE
Error with bullet and uniform_notifier - rails 4 ruby 2.2.4

### ISSUE THREAD

**Issue by robertoboldi** [flyerhzm/bullet#464]
I'm trying to use bullet gem to avoid N+1 queries in my website. I've used it until some months ago, then it stopped to work. I got this only today.

when i start my localhost i get this error message:

/Users/carcarlo/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require':/Users/carcarlo/.rvm/gems/ruby-2.2.4/gems/uniform_notifier-1.12.0/lib/uniform_notifier/base.rb:37: syntax error, unexpected <<, expecting keyword_end (SyntaxError)
  <<~CODE
    ^/Users/carcarlo/.rvm/gems/ruby-2.2.4/gems/uniform_notifier- 1.12.0/lib/uniform_notifier/base.rb:38: syntax error, unexpected '<', expecting keyword_end <script #{attributes_string}>/*<![CDATA[*/
     ^ target of repeat operator is not specified: /*]]>*/
it is clear that is an error in the file base.rb of the gem uniform_notifier (dependency of bullet), but what can I do to get it working on my system? I tried to force the installation of uniform_notifier to an older version (actual is 1.12.1) but it is locked to 1.12.0

this application is written using ruby 2.2.4 and rails 4.2.5

I don't know what other information are needed for any kind of support.

thanks

**Comment by mattboldt** [comment]
Same here. Ruby `2.2.4`, Rails `4.1.16`.  Using `gem 'bullet', '~> 5.7.6'` resolved this for me.

**Comment by ritesh-indexnine** [comment]
Hey, I'm getting same error, using Rails 4.0.2 & Ruby 2.1.0 tried latest version of Bullet gem, also tried 5.7.6. Please help me to get it working @flyerhzm @mattboldt

**Comment by ritesh-indexnine** [comment]
Found problem with heredoc definition in couple of files, converted <<~CODE to <<-CODE and it worked.
