### ISSUE TITLE
triger a preload error on manual preloads on rails 6

### ISSUE THREAD

**Issue by mahha0705** [flyerhzm/bullet#477]
I upgrade rails from 5.2 to 6 and bullet is 6.0.2

tests the following with request spec and response return 500 with UnoptimizedQueryError

```ruby 
  comment.update(post: post)
```

``` ruby
  Unused Eager Loading detected
  Comment => [:post]
  Remove from your finder: :includes =>  #[:post]
```

Pull request that merged #444 may be fix this error. 
cause code still remains on only active_record60.rb.

**Comment by flyerhzm** [comment]
@mahha0705 I have already made the same change to `active_record60.rb`
