### ISSUE TITLE
Bullet's inline JavaScript not compatible with Content Security Policy

### ISSUE THREAD

**Issue by connorshea** [flyerhzm/bullet#478]
I use a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) in my Rails app, and it's pretty restrictive. It blocks all inline JavaScript to prevent user input from being able to abuse arbitrary `<script>` tags if the sanitizer fails or I make a mistake in my code.

It still allows inline JavaScript if it includes a valid `nonce` tag. The nonce is essentially a randomly generated string that changes every request, and verifies that the inline JS was loaded from the server.

CSP support [was added to Rails in 5.2](https://blog.bigbinary.com/2018/10/23/rails-5-2-adds-dsl-for-configuring-content-security-policy-header.html), and can be configured in `config/initializers/content_security_policy.rb`.

This is what it looks like in my app, with the console open:

<img width="1437" alt="Screen Shot 2019-09-22 at 1 41 42 PM" src="https://user-images.githubusercontent.com/2977353/65393517-bcfe3d00-dd3e-11e9-9821-fc0860953d2f.png">

Bullet's notifications aren't able to be closed because the JS that provides that functionality is never allowed to load.

### Suggested fix

The code in Bullet for adding this JS is here:

https://github.com/flyerhzm/bullet/blob/2ada165a7262daa4ab4eeb2f0a11c84afe285e72/lib/bullet/rack.rb#L111

Unfortunately, I'm not sure how to get a nonce from Rails without using a [`javascript_include_tag`](https://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-javascript_include_tag), which wouldn't be usable in a plain Rack app. So I'm not sure how best to fix this. You might be able to call the [`content_security_policy_nonce`](https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/actionpack/lib/action_dispatch/http/content_security_policy.rb#L93) method in ActionDispatch, but I'm not sure.

### Reproduction steps 

- Clone https://github.com/connorshea/VideoGameList (in case I fix the error, the specific commit right now is `389c4640a66a1303bb3634e367a7f346cbcd0181`).
- Follow the setup instructions in the README.
- Run `bundle exec rails db:seed` to get the database seeded, then host the server with `rails s` (and the webpack dev server in another terminal, with `ruby ./bin/webpack-dev-server`).
- Go to `localhost:3000/activity` to see a Bullet warning.
- Open the browser console to see a CSP warning, and try to close the Bullet notification with the 'x', it won't close because the JavaScript has been blocked by the CSP.

You can pretty much reproduce it with any Rails app that has Bullet and a CSP that blocks inline JS.

**Comment by flyerhzm** [comment]
@connorshea maybe you can change `content_security_policy.rb` as https://github.com/turbolinks/turbolinks/issues/430#issuecomment-518326242

**Comment by connorshea** [comment]
The reason I’d prefer not to do that is because I could shoot myself in the foot by making development and production not match. Things that work in development would break in production.

**Comment by flyerhzm** [comment]
@connorshea it set different configurations for development and production, won't break in production.
