### ISSUE TITLE
`Uncaught TypeError: Cannot read property 'name' of undefined` javascript error

### ISSUE THREAD

**Issue by pcraston** [flyerhzm/bullet#487]
We're getting a `Uncaught TypeError: Cannot read property 'name' of undefined` error on this line of bullet_xhr.js:

https://github.com/flyerhzm/bullet/blob/9dd22aa583a615afa35a7681cfadbc97ff8b5ffa/lib/bullet/bullet_xhr.js#L13

Seems like `window.XMLHttpRequest.prototype.open` is undefined. Happens on every page of our rails app.

Any idea what it could be?

Thanks!

**Comment by jklimke** [comment]
Happens in out rails app as well. Any ideas how to avoid / fix this ?

**Comment by pcraston** [comment]
seems to be fixed in the latest version so closing

**Comment by hicklin-james** [comment]
We are still seeing this issue on the latest version of the gem - anyone come up with a solution?

**Comment by hicklin-james** [comment]
Chrome v102.0.5005.115 on Mac OS. I see a similar error on Safari too though when the footer is enabled.

Safari error:
```
TypeError: undefined is not an object (evaluating 'oldOpen.name')
```

**Comment by flyerhzm** [comment]
Could you try the `bugs/fix-xmlhttprequest-prototype-open-name` branch?  I’ve implemented a fix, but I’m unable to verify it myself.
