### ISSUE TITLE
Threadsafe whitelist

### ISSUE THREAD

**Issue by matiasgarcia** [flyerhzm/bullet#490]
We have Bullet configured in our test suite to raise an error if we have an issue.

The problem with this is that some of our tests fail because of the "Unused Eager Loading" warning. That makes sense for the context of the test where the loaded association isn't used at all but it doesn't affect the performance at all and we don't need to fine-tune each use case to know what to load or not.

When this happens, we add it to the whitelist. The problem with this is that since the whitelist is applied globally, we might be missing the error in places where it makes sense to be raised. So at first, I thought that maybe we could configure an RSpec hook to create and delete the whitelist as needed for the context of the spec.

However, could it be that this whitelist is not thread-safe? If it isn't, maybe I can build something around it but I wanted to confirm with the maintainers.

Thanks.

**Comment by jeffblake** [comment]
It isn't, and neither is `Bullet.enable`. I'd love to see these become threadsafe so I can run parallel tests, selectively opting in to raise Bullet errors on a test by test basis.

**Comment by flyerhzm** [comment]
@matiasgarcia I have make whitelist threadsafe in latest master branch

@jeffblake I don't think it's necessary to make enabled thread safe.
