### ISSUE TITLE
Consider renaming "whitelist" methods to somethinge else

### ISSUE THREAD

**Issue by rhymes** [flyerhzm/bullet#510]
Following the example of https://github.com/rails/rails/issues/33677 and https://github.com/thepracticaldev/dev.to/issues/7147 I'm proposing to take into consideration the replacement of words like `whitelist`/`blacklist` from Bullet's source code.

Possible alternatives: `allow`, `valid`, `permitted`.

According to a quick search - https://github.com/flyerhzm/bullet/search?q=whitelist&unscoped_q=whitelist - it's mostly `add_whitelist`/`clear_whitelist`,`reset_whitelist` and so on.

A possible solution would be to add alternative methods and deprecation notices and then remove them a couple of releases down the line or something like that.

I can work on the initial PR if agreed.

Thank you!

**Comment by flyerhzm** [comment]
@rhymes I'm open to it, feel free to create a PR.
