### ISSUE TITLE
New release for Rails 6.1.0

### ISSUE THREAD

**Issue by connorshea** [flyerhzm/bullet#530]
There's a commit from a few months ago that adds support for Rails 6.1 (5bfc82a5949b964793dab2d7c66c404d0a004895), but it hasn't been released to RubyGems.org yet. Could we get a new release?

**Comment by Thornolf** [comment]
Hey ! Just a small reminder, it would be awesome if you could do it ♥️ Thank you for everything you do on this project !

**Comment by zaratan** [comment]
@flyerhzm is there anything missing for supporting rails 6.1 ? Can I help in any way ?

**Comment by flyerhzm** [comment]
I've released version 6.1.2, please give it a try

**Comment by zaratan** [comment]
@flyerhzm Works perfectly. Thanks.
