### ISSUE TITLE
console notification setting not working

### ISSUE THREAD

**Issue by elalemanyo** [flyerhzm/bullet#531]
Hi,
I am getting some errors in the browser provoked from Bullet gem, because I don't really need the console notifications I update bullet settings like this:
```
Bullet.enable = true
Bullet.rails_logger = true
Bullet.console = false
Bullet.add_footer = false
```
But nothing change, I am still getting some errors provoked from bullet inside the browser console. Am I doing something wrong?

BTW the errors that I get are:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/3856862/101162878-324bea00-3633-11eb-8be4-4a9b1acdb704.png">

**Comment by flyerhzm** [comment]
@elalemanyo what's your browser? I didn't see this error in mac chrome.

**Comment by elalemanyo** [comment]
@flyerhzm I am also using Chrome 🤷
But what I don't understand is why Bullet is adding some js even I add the setting to don't do it

**Comment by flyerhzm** [comment]
@elalemanyo please also disable `Bullet.add_footer`

**Comment by elalemanyo** [comment]
@flyerhzm I add `Bullet.add_footer` but nothing change 😞
My config looks like this:
```
Rails.application.config.after_initialize do
  Bullet.enable = true
  Bullet.rails_logger = true
  Bullet.console = false
  Bullet.add_footer = false
end
```

the error that I am getting are:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/3856862/102061134-5eb1f400-3df3-11eb-9e46-2aaa8888e27f.png">

<img width="838" alt="image" src="https://user-images.githubusercontent.com/3856862/102061090-4b068d80-3df3-11eb-9a1c-3f070ce5e206.png">

**Comment by flyerhzm** [comment]
@elalemanyo I have fixed it on the master branch, will be ready in the next release.

**Comment by elalemanyo** [comment]
Thanks @flyerhzm! Now works great, I have now a clean console in the browser.

Thank you for this nice gem and for helping me!

**Comment by bogn83** [comment]
@elalemanyo please close the issue
