### ISSUE TITLE
Support for Sentry Warning Instead of Errors

### ISSUE THREAD

**Issue by pacarvalho** [flyerhzm/bullet#535]
I am currently using this gem with the option `Bullet.sentry = true`. Is it possible to have the Sentry error messages generated by the gem be of level `warning` instead of `error`? 

If not, please add it as a feature request.

**Comment by tejasbubane** [comment]
@flyerhzm would it be ok to have a separate flag `sentry_level` ?

**Comment by pacarvalho** [comment]
> @flyerhzm would it be ok to have a separate flag `sentry_level` ?

That would be great!

**Comment by flyerhzm** [comment]
@pacarvalho @tejasbubane is it working to set `Bullet.sentry = { level: :warning}`?

**Comment by pacarvalho** [comment]
I am no longer on the project that used this functionality. However, if the ability to set Sentry level was added this issue can be closed 😄
