### ISSUE TITLE
sentry-raven is depreciated, we need to upgrade to sentry-ruby

### ISSUE THREAD

**Issue by VSSilva233** [flyerhzm/bullet#588]
the sentry updated and if you use sentry-ruby with bullet in the project and the option .sentry = true gives an error because the bullet tries to notify the sentry in the outdated way

https://github.com/getsentry/sentry-ruby

**Comment by tejasbubane** [comment]
Seems like it is already supported: https://github.com/flyerhzm/bullet/issues/543
