### ISSUE TITLE
No such middleware to insert before: ActionDispatch::ContentSecurityPolicy::Middleware (RuntimeError)

### ISSUE THREAD

**Issue by dansajner** [flyerhzm/bullet#637]
Update from 7.0.4 to 7.0.5 and receiving this exception initializing my rails application:

```
ruby/gems/3.1.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/stack.rb:162:in `assert_index': No such middleware to insert before: ActionDispatch::ContentSecurityPolicy::Middleware (RuntimeError)
```

**Comment by MichaelLah** [comment]
This seems to occur only for API-only Rails applications. Rails [does not load this middleware](https://github.com/rails/rails/blob/157920aead96865e3135f496c09ace607d5620dc/railties/lib/rails/application/default_middleware_stack.rb#L69-L71) when it's API-only.

It seems despite the middleware not being included in the stack, the constant `ActionDispatch::ContentSecurityPolicy::Middleware` is still defined, which trips up this logic [here](https://github.com/flyerhzm/bullet/commit/e2a5b5e8edb3a6bb46c91c9856fec2f5367e67a9)

You can reproduce this issue on a fresh API-only Rails application. I tried this with rails 7.0:

- `rails new example_application --api`
- `bundle add bullet`
- `rails c`
