### ISSUE TITLE
Include in test as well?

### ISSUE THREAD

**Issue by MyklClason** [flyerhzm/bullet#645]
The current instructions can result in errors for at least some version of ruby if when rspec runs as it is not in the "test" group.

The error generated does not make it obvious that the issue is with the bullet gem.
https://stackoverflow.com/questions/47320772/rails-runtimeerror-cant-modify-frozen-array-when-running-rspec-in-rails

**Comment by ronald2wing** [comment]
I don't think it should include in test because it is for development however the bundle exec rails g bullet:install will add to test config.
