### ISSUE TITLE
Bullet does not support active_record 7.0.6 

### ISSUE THREAD

**Issue by mayurpathak** [flyerhzm/bullet#688]
```
rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'bullet'.
Gem Load Error is: Bullet does not support active_record 7.0.6 yet
Backtrace for gem load error is:
```

anyone help me please

**Comment by flyerhzm** [comment]
@mayurpathak what bullet version are you using?

**Comment by prdanelli** [comment]
Similar, i'm seeing: 

```
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'bullet'.
Gem Load Error is: Bullet does not support active_record 7.1.1 yet
```

**Comment by mayurpathak** [comment]
> bullet

gem vesrion >>> 7.1. 2

**Comment by mayurpathak** [comment]
> Similar, i'm seeing:
> 
> ```
> rake aborted!
> Bundler::GemRequireError: There was an error while trying to load the gem 'bullet'.
> Gem Load Error is: Bullet does not support active_record 7.1.1 yet
> ```

when it will start support ???

**Comment by flyerhzm** [comment]
@prdanelli @mayurpathak I just created bullet_test repo https://github.com/flyerhzm/bullet_test with rails 7.1.1 and bullet 7.1.2, it works well.

**Comment by prdanelli** [comment]
Thank you @flyerhzm for the time you've put into this project and its continued support.

**Comment by prdanelli** [comment]
@flyerhzm Do you have a timeline for pushing the Rails 7.1 fix?

**Comment by flyerhzm** [comment]
@prdanelli I don't get it, bullet 7.1.2 already contains all the commits on the main branch.

**Comment by Annastacia-dev** [comment]
> @prdanelli I don't get it, bullet 7.1.2 already contains all the commits on the main branch.

If it helps this only happens when you specify the bullet gem version i.e adding `gem 'bullet', '~> 6.1'` to your Gemfile  gives you the above error but `gem 'bullet'` doesn't

**Comment by flyerhzm** [comment]
if you get such error, probably you installed the wrong version of bullet
bullet 6 starts to suppport rails 6 and bullet 7 starts to support rails 7
