### ISSUE TITLE
Problem with counter_cache_enable and raise

### ISSUE THREAD

**Issue by vitaliiorlov** [flyerhzm/bullet#695]
Hi!
I've updated to Bullet to `7.1.3` from `7.1.2` and have such issue. My configuration:
```
...
Bullet.raise                = true
Bullet.counter_cache_enable = false
```

`7.1.2` won't raise exception with such configuration.
`7.1.3` will raise exception with such configuration

**Comment by flyerhzm** [comment]
@vitaliiorlov I didn't make any change to configuration in 7.1.3.

I tried to add these 2 configurations to [bullet_test](https://github.com/flyerhzm/bullet_test), and I didn't see any problem.
