### ISSUE TITLE
New gem version

### ISSUE THREAD

**Issue by chenzheng-jora** [flyerhzm/bullet#697]
Hey team, thanks for the great work for making bullet compatible with Mongo8x with #689, appreciate that! 
Can I kindly request for a new version release of the gem including the fix so that we don't need to reference Github repo and branch name for bundler. Asking because we are having following issue building a docker image and some search results indicating this can be fixed by removing the reference to the git repo. Thanks

```
https://github.com/flyerhzm/bullet.git (at main@e48c6c8) is not yet checked out. Run `bundle install` first.
```

**Comment by flyerhzm** [comment]
@chenzheng-jora I have just released version 7.1.5.
