### ISSUE TITLE
Bullet does not support active_record 7.1.3.2 yet

### ISSUE THREAD

**Issue by DogAndCode** [flyerhzm/bullet#702]
10:08:59 web.1  | Gem Load Error is: Bullet does not support active_record 7.1.3.2 yet
10:08:59 web.1  | Backtrace for gem load error is:
10:08:59 web.1  | /home/pc/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bullet-6.1.5/lib/bullet/dependency.rb:33:in `active_record_version'
10:08:59 web.1  | /home/pc/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bullet-6.1.5/lib/bullet.rb:14:in `<module:Bullet>'
10:08:59 web.1  | /home/pc/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bullet-6.1.5/lib/bullet.rb:11:in `<main>'

**Comment by flyerhzm** [comment]
@DogAndCode please update bullet to 7.1.x
