### ISSUE TITLE
Bullet Gem Incompatibility with ActiveRecord 8.0.0.beta1

### ISSUE THREAD

**Issue by lazyscript05** [flyerhzm/bullet#718]
Description
I encountered an error while trying to use the Bullet gem with ActiveRecord 8.0.0.beta1. The Bullet gem version is 7.2.0, and it appears that it does not support the beta version of ActiveRecord that I am using.

Error Message:
```
/home/user/.rvm/gems/ruby-3.3.5/gems/bundler-2.5.20/lib/bundler/runtime.rb:63:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'bullet'. (Bundler::GemRequireError)
Gem Load Error is: Bullet does not support active_record 8.0.0.beta1 yet
Backtrace for gem load error is:
    /home/user/.rvm/gems/ruby-3.3.5/gems/bullet-7.2.0/lib/bullet/dependency.rb:39:in `active_record_version'
    /home/user/.rvm/gems/ruby-3.3.5/gems/bullet-7.2.0/lib/bullet.rb:14:in `<module:Bullet>'
    /home/user/.rvm/gems/ruby-3.3.5/gems/bullet-7.2.0/lib/bullet.rb:11:in `<main>'
    <internal:/home/user/.rvm/rubies/ruby-3.3.5/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
```

Steps to Reproduce
Use Ruby version 3.3.5.
Install Bullet gem version 7.2.0.
Attempt to run the application with ActiveRecord 8.0.0.beta1.

Expected Behavior
The Bullet gem should be compatible with ActiveRecord 8.0.0.beta1, or a message should indicate that a compatible version of Bullet is required.

Actual Behavior
The application fails to load the Bullet gem due to an incompatibility issue with ActiveRecord 8.0.0.beta1.

Additional Information
Ruby version: 3.3.5
Bullet version: 7.2.0
ActiveRecord version: 8.0.0.beta1

Thank you for your attention to this issue!

**Comment by augustosamame** [comment]
Just got bitten by this one too. I don't see anything in ActiveRecord that may break this gem. I will fork bullet and force it to install and report back

**Comment by augustosamame** [comment]
working fine from my fork. Sent a PR for it to be merged into testing branch

**Comment by lazyscript05** [comment]
> working fine from my fork. Sent a PR for it to be merged into testing branch

Thank you @augustosamame.

**Comment by epugh** [comment]
Bumped into this too..

**Comment by kristian-nst** [comment]
Pls 🙏

**Comment by jmaino** [comment]
Rails 8.0.0 is now officially released;  can't be run w/ bullet given the above.
Thank you

**Comment by flyerhzm** [comment]
bullet 8.0.0 is released to support rails 8
