### ISSUE TITLE
Bullet with non-Mongoid MongoDB calls?

### ISSUE THREAD

**Issue by tcblight** [flyerhzm/bullet#723]
Hi,

This is a weird request that seems unlikely to be possible.

I've used Bullet in the "ideal path" situation with Rails and ActiveRecord before and loved it. It was very helpful to deal with poorly performing APIs due to the N+1 query problem.

But my current employer is in a non-ideal context for using it - Padrino (a Sinatra variant, which appears to be supported) and using MongoDB calls without Mongoid - just using the mongo gem and the things we've built up around it. (No ActiveRecord either)

Is there a way I could still use Bullet to instrument these calls to detect repeated queries in loops?

**Comment by flyerhzm** [comment]
@tcblight no, it's not possible. Bullet adds some hooks in the ORM (activerecord, mongoid) to find out N+1 queries.
