### ISSUE TITLE
Bullet does not support active_record 7.2.2 yet

### ISSUE THREAD

**Issue by jessicazappa** [flyerhzm/bullet#726]
> Bundler::GemRequireError:
>   There was an error while trying to load the gem 'bullet'.
>   Gem Load Error is: Bullet does not support active_record 7.2.2 yet
>   Backtrace for gem load error is:
>   /usr/local/bundle/gems/bullet-7.1.6/lib/bullet/dependency.rb:37:in `active_record_version'

**Comment by vprigent** [comment]
ActiveRecord 7.2 was added as part of Bullet 7.2
https://github.com/flyerhzm/bullet/compare/7.1.6...7.2.0

**Comment by flyerhzm** [comment]
@jessicazappa yes, pleas use bullet >= 7.2.0 for AR 7.2.0.
