### ISSUE TITLE
bullet and squeel

### ISSUE THREAD

**Issue by thomasfedb** [flyerhzm/bullet#80]
When used alongside [Squeel](https://github.com/ernie/squeel) bullet will detect N+1 queries correctly but will report unused eager loadings in error.

This may be due to Bullet hooking into AR/ARel at a point that results in it being unaware of Squeel queries.

Fantastic tool, just wish I could use it alongside Squeel.

**Comment by azzz** [comment]
+1

**Comment by pyromaniac** [comment]
+1

**Comment by Tei** [comment]
+1
