### ISSUE TITLE
Bullet sometimes makes the page go 10+ times slower

### ISSUE THREAD

**Issue by Intrepidd** [flyerhzm/bullet#82]
Hi,

Here is the problem.

I had this page that was really long (50secs), development.log told me the page was rendered in 5 secs, which is still long but better.

After hours of research, i disabled bullet, and the page now renders in 5 secs as the development.log claims.

Thanks !

**Comment by hmcfletch** [comment]
I am running into this issue as well running under Rails 4.2. I ran into some issues with N+1 queries so I decided to add in Bullet to help find these in the future before we get to production.

I have a page that takes ~7 seconds to load, but when I added Bullet, it took another 14 minutes for the page to finally render.

Excerpt from my logs today:
```
[2015-01-21 14:25:25(51955) INFO] Completed 200 OK in 6975ms (Views: 6629.5ms | ActiveRecord: 155.7ms)
[2015-01-21 14:39:33(51955) WARN] user: Les
/invoices
N+1 Query detected
...
```
The bullet log statements printed the same time my page rendered, 14 minutes after Rails had finished it's business.

I am only seeing the issue on pages with tons of queries and includes. This page in particular has one query that has between 10-15 includes (some nested). Other pages are behaving just fine.
